package templates

var templateHeader = `
// Code generated by Yggdrasill.
// Generated at {{now}}
`
var tableModelTemplate = `
package {{param "packageName"}}
{{ if .Imports }}
import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)
{{end}}

{{$structName := CamelizeStr .Name true}}

type {{$structName}} struct {
{{- range .Columns}}
	{{CamelizeStr .Name true}} {{.GoType}} ` + "{{.Tag}}" + `
{{- end}}
}
{{$firstChar := FirstCharacter .Name}}

func ({{$firstChar}} {{$structName }}) TableName() string {
	return "{{.Name}}"
}
`
